services:
  hyprfolio:
    image: ghcr.io/christian-deleon/hyprfolio:latest
    ports:
      - '8080:8080'
    volumes:
      - .:/config
    environment:
      - ASTRO_ADAPTER=node
    env_file:
      - .env
